### ISSUE TITLE
copy module: my copy module keep returning error

### ISSUE THREAD

**Issue by Paulanisiobi** [jbichene95/projects-group#5]
/home/ubuntu/ansible1/tetris-light/static.yml

**Comment by aitech-ng** [comment]
Please paste the link to your github repo here, so we can check the playbook

**Comment by Paulanisiobi** [comment]
https://github.com/Paulanisiobi/ANSIBLE-PROJECT.git

**Comment by jbichene95** [comment]
> https://github.com/Paulanisiobi/ANSIBLE-PROJECT.git

Hi  Mr Paul , kindly post a repo with your playbook in it

**Comment by jbichene95** [comment]
https://github.com/Paulanisiobi/tetris-light/blob/c2485ccb430ed7912aeefa9a38f98fed624ca36e/tetris.yml#L24-L28

Hi mr paul , consider copying first to the /var/www/html/<new folder>, this will help avoid permissions issues you might encounter on the step above, however using "0777" might work, but it's  not good practice , but if it works ...it's allowed for now  .


https://github.com/Paulanisiobi/tetris-light/blob/c2485ccb430ed7912aeefa9a38f98fed624ca36e/tetris.yml#L31-L36
as for your copy refrenced above , consider setting a copy parameter called "follow"  to do copy and replace for the default config on the server.

if these solutions don't work , kindly provide  more info on the error you've gotten
